### PR TITLE
Merge a floating commit into master

### PR DESCRIPTION
**Pull request by peroxyacyl**
We need this because this commit is referred as submodule

### CODE REVIEW

**Comment by tokoro10g** [comment]
Can we just use the latest upstream as this is already merged?
https://github.com/ouster-lidar/ouster_example/pull/566
https://github.com/ouster-lidar/ouster_example/issues/588

**Comment by peroxyacyl** [comment]
@tokoro10g Ok. Can you update ouster-ros repo?

**Comment by tokoro10g** [comment]
@peroxyacyl 
Done: https://github.com/GITAI/ouster-ros/pull/2

**Comment by peroxyacyl** [comment]
I will archive this repo

**Pull request closed without merging**
